print("---- Pasos para preparar una Torta ----")
print("Buscar el recetario de torta")
print("Elegir la torta a preparar")
print("Buscar los ingredientes")
print("Mesclar los ingredientes")
print("Calentar el horno")
print("Colocar en un molde todos los ingredientes mesclados")
print("Llevar al horno")
print("Esperar la coccion por 30 minutos")
print("Retirar la torta del horno")
