print("---- Pasos para preparar un Pastel ----")
print("Buscar el recetario de pastel")
print("Elegir la pastel a preparar")
print("Buscar los ingredientes")
print("Mesclar los ingredientes")
print("Calentar el horno")
print("Colocar en un molde todos los ingredientes mesclados")
print("Llevar al horno")
print("Esperar la coccion por 30 minutos")
print("Retirar la pastel del horno")
